#!/usr/bin/env -S uv run
"""Which file names `Syntax.guess_lexer` resolves to a **promoted** family.

`_read_output_renderable` highlights a `Read` result by `Syntax.guess_lexer(path, code)`,
which is Pygments' `guess_lexer_for_filename`: every lexer whose `filenames` or
`alias_filenames` globs match is a candidate, each is scored by its own `analyse_text`,
and the winner is the maximum by `(score, is primary, priority, class name)`.

**Porting every `analyse_text` is not needed, and the reason is measurable.** Only the
seven promoted families change what a fence renders; everything else is plain either
way. Of the globs those seven claim, all but `*.js` have exactly one candidate, so the
filename decides. `*.js` has seven — `JavascriptLexer` plus six template delegates —
and a delegate wins whenever its score clears zero, because `JavascriptLexer` scores
zero and only loses to something strictly higher.

So this writes two things: the globs that reach a promoted family, and the note that
`*.js` is conditional. The delegation test itself is ported in `session_render.rs`.

**`*.sql` is deliberately absent.** `SqlLexer`, `TransactSqlLexer` and `SqlJinjaLexer`
all claim it, all tie at zero, and the tie-break is the class name — so
`TransactSqlLexer` always wins and a `Read` of a `.sql` file renders **plain**. SQL is
promoted for fences and unreachable here.
"""

from __future__ import annotations

import argparse
import fnmatch
from pathlib import Path

from pygments.lexers import _iter_lexerclasses
from rich.syntax import Syntax

PROMOTED_DISPLAY_NAMES = {
    "TypeScript": "TypeScript",
    "TSX": "TSX",
    "Python": "Python",
    "JavaScript": "JavaScript",
    "SQL": "SQL",
    "Bash": "Bash",
    "JSON": "JSON",
}


def candidates(name: str) -> list:
    out = []
    for lexer in _iter_lexerclasses():
        primary = any(fnmatch.fnmatch(name, pattern) for pattern in lexer.filenames)
        alias = any(fnmatch.fnmatch(name, pattern) for pattern in lexer.alias_filenames)
        if primary or alias:
            out.append(lexer if primary else lexer)
            out[-1]._is_primary_for_probe = primary
    return out


def sample_name(glob: str) -> str:
    return glob.replace("*", "sample") if "*" in glob else glob


# **A battery rather than an argument.** A glob's candidates are ranked by scores this
# port does not compute, so whether the promoted lexer actually wins is settled by
# asking Pygments with content that turns each analyser on and off.
PROBES = (
    "value = 1\n",
    "const a = `x ${b} y`;\n",
    "<% erb %>\n",
    "#!/usr/bin/env python\nvalue = 1\n",
    "#!/bin/bash\necho hi\n",
    '<root><child>x</child></root>\n',
    "{% block a %}{% endblock %}\n",
    "<?php echo 1; ?>\n",
    "{if $x}{/if}\n",
    "DECLARE @x INT;\nSELECT * FROM t;\n",
    'py:match="x"\n',
)


def verdict(glob: str, promoted) -> str:
    """`unconditional`, `conditional`, or `never`, measured against Pygments."""
    name = sample_name(glob)
    if len(candidates(name)) == 1:
        return "unconditional"
    answers = set()
    for probe in PROBES:
        try:
            answers.add(Syntax.guess_lexer(name, probe))
        except Exception:
            answers.add("default")
    wins = {alias for alias in answers if alias in promoted.aliases}
    if not wins:
        return "never"
    if len(answers) == 1:
        return "unconditional"
    # Two conditionals exist and each has its own rule, ported by name in
    # `session_render.rs`. A third would be a new rule rather than a new row.
    return {"*.js": "js-delegates", "*.sc": "python-shebang"}[glob]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    options = parser.parse_args()

    rows: list[tuple[str, str, bool]] = []
    for lexer in _iter_lexerclasses():
        display = PROMOTED_DISPLAY_NAMES.get(lexer.name)
        if display is None:
            continue
        for glob in lexer.filenames:
            answer = verdict(glob, lexer)
            if answer == "never":
                print(f"  never reachable: {glob} -> {lexer.name}")
                continue
            rows.append((glob, display, answer))
    rows.sort()

    lines = [
        "//! Which file names a `Read` result's highlight resolves to a promoted family.",
        "//!",
        "//! Generated by",
        "//! `teammates/cutover-finisher/probes/generate_read_lexers.py`. Do not edit.",
        "//!",
        "//! Every glob here has exactly one Pygments candidate unless `conditional` is",
        "//! set, in which case a template delegate can take the file away from the",
        "//! promoted lexer and `session_render` runs the delegation test.",
        "",
        "/// `(glob, promoted display name, rule)`, sorted. The rule is",
        "/// `unconditional`, or the name of a content test `session_render` runs.",
        "pub const READ_PROMOTED_FILENAMES: &[(&str, &str, &str)] = &[",
    ]
    for glob, display, rule in rows:
        lines.append(f'    ("{glob}", "{display}", "{rule}"),')
    lines.append("];")
    Path(options.out).write_text("\n".join(lines) + "\n")
    print(f"{len(rows)} globs -> {options.out}")
    for glob, display, rule in rows:
        if rule != "unconditional":
            print(f"  {rule}: {glob} -> {display}")


if __name__ == "__main__":
    main()
