//! Which Pygments lexer a fence's language tag resolves to.
//!
//! Generated from Pygments 2.19.2 by
//! `teammates/message-renderer/probes/generate_lexer_aliases.py`. Do not edit.
//!
//! `CodeBlock.create` takes the first word of a fence's info string, or `text`,
//! and `Syntax` looks that name up. **A tag with no entry here finds no lexer**,
//! and Rich then falls back to its plain-text lexer — which is the same rendering
//! as the `text` tag, and is exactly reproducible with no lexer at all.

/// Every Pygments alias, lowercased, paired with its lexer's display name.
/// Sorted, so a lookup is a binary search.
pub const LEXER_ALIASES: &[(&str, &str)] = &[
    ("abap", "ABAP"),
    ("abl", "OpenEdge ABL"),
    ("abnf", "ABNF"),
    ("aconf", "ApacheConf"),
    ("actionscript", "ActionScript"),
    ("actionscript3", "ActionScript 3"),
    ("ada", "Ada"),
    ("ada2005", "Ada"),
    ("ada95", "Ada"),
    ("adl", "ADL"),
    ("agda", "Agda"),
    ("aheui", "Aheui"),
    ("ahk", "autohotkey"),
    ("alloy", "Alloy"),
    ("ambienttalk", "AmbientTalk"),
    ("ambienttalk/2", "AmbientTalk"),
    ("amdgpu", "AMDGPU"),
    ("ampl", "Ampl"),
    ("androidbp", "Soong"),
    ("ansys", "ANSYS parametric design language"),
    ("antlr", "ANTLR"),
    ("antlr-actionscript", "ANTLR With ActionScript Target"),
    ("antlr-as", "ANTLR With ActionScript Target"),
    ("antlr-c#", "ANTLR With C# Target"),
    ("antlr-cpp", "ANTLR With CPP Target"),
    ("antlr-csharp", "ANTLR With C# Target"),
    ("antlr-java", "ANTLR With Java Target"),
    ("antlr-objc", "ANTLR With ObjectiveC Target"),
    ("antlr-perl", "ANTLR With Perl Target"),
    ("antlr-python", "ANTLR With Python Target"),
    ("antlr-rb", "ANTLR With Ruby Target"),
    ("antlr-ruby", "ANTLR With Ruby Target"),
    ("apache", "ApacheConf"),
    ("apacheconf", "ApacheConf"),
    ("apdl", "ANSYS parametric design language"),
    ("apl", "APL"),
    ("applescript", "AppleScript"),
    ("arduino", "Arduino"),
    ("arexx", "Rexx"),
    ("arrow", "Arrow"),
    ("art", "Arturo"),
    ("arturo", "Arturo"),
    ("as", "ActionScript"),
    ("as3", "ActionScript 3"),
    ("asc", "ASCII armored"),
    ("asm", "GAS"),
    ("asn1", "ASN.1"),
    ("aspectj", "AspectJ"),
    ("aspx-cs", "aspx-cs"),
    ("aspx-vb", "aspx-vb"),
    ("asy", "Asymptote"),
    ("asymptote", "Asymptote"),
    ("at", "AmbientTalk"),
    ("augeas", "Augeas"),
    ("autohotkey", "autohotkey"),
    ("autoit", "AutoIt"),
    ("awk", "Awk"),
    ("b3d", "BlitzBasic"),
    ("bare", "BARE"),
    ("basemake", "Base Makefile"),
    ("bash", "Bash"),
    ("basic", "QBasic"),
    ("bat", "Batchfile"),
    ("batch", "Batchfile"),
    ("bazel", "Python"),
    ("bbcbasic", "BBC Basic"),
    ("bbcode", "BBCode"),
    ("bc", "BC"),
    ("bdd", "Bdd"),
    ("be", "Berry"),
    ("befunge", "Befunge"),
    ("berry", "Berry"),
    ("bf", "Brainfuck"),
    ("bib", "BibTeX"),
    ("bibtex", "BibTeX"),
    ("blitzbasic", "BlitzBasic"),
    ("blitzmax", "BlitzMax"),
    ("blueprint", "Blueprint"),
    ("bmax", "BlitzMax"),
    ("bnf", "BNF"),
    ("boa", "Boa"),
    ("boo", "Boo"),
    ("boogie", "Boogie"),
    ("bp", "Soong"),
    ("bplus", "BlitzBasic"),
    ("bqn", "BQN"),
    ("brainfuck", "Brainfuck"),
    ("bro", "Zeek"),
    ("bsdmake", "Makefile"),
    ("bst", "BST"),
    ("bst-pybtex", "BST"),
    ("bugs", "BUGS"),
    ("c", "C"),
    ("c#", "C#"),
    ("c++", "C++"),
    ("c++-objdumb", "cpp-objdump"),
    ("c-objdump", "c-objdump"),
    ("ca65", "ca65 assembler"),
    ("cadl", "cADL"),
    ("camkes", "CAmkES"),
    ("capdl", "CapDL"),
    ("capnp", "Cap'n Proto"),
    ("carbon", "Carbon"),
    ("cbmbas", "CBM BASIC V2"),
    ("cddl", "CDDL"),
    ("ceylon", "Ceylon"),
    ("cf3", "CFEngine3"),
    ("cfc", "Coldfusion CFC"),
    ("cfengine3", "CFEngine3"),
    ("cfg", "INI"),
    ("cfm", "Coldfusion HTML"),
    ("cfs", "cfstatement"),
    ("chai", "ChaiScript"),
    ("chaiscript", "ChaiScript"),
    ("chapel", "Chapel"),
    ("charmci", "Charmci"),
    ("cheetah", "Cheetah"),
    ("chpl", "Chapel"),
    ("cirru", "Cirru"),
    ("cl", "Common Lisp"),
    ("clay", "Clay"),
    ("clean", "Clean"),
    ("clipper", "FoxPro"),
    ("clj", "Clojure"),
    ("cljs", "ClojureScript"),
    ("clojure", "Clojure"),
    ("clojurescript", "ClojureScript"),
    ("cmake", "CMake"),
    ("cobol", "COBOL"),
    ("cobolfree", "COBOLFree"),
    ("codeql", "CodeQL"),
    ("coffee", "CoffeeScript"),
    ("coffee-script", "CoffeeScript"),
    ("coffeescript", "CoffeeScript"),
    ("comal", "COMAL-80"),
    ("comal80", "COMAL-80"),
    ("common-lisp", "Common Lisp"),
    ("componentpascal", "Component Pascal"),
    ("console", "Bash Session"),
    ("control", "Debian Control file"),
    ("coq", "Coq"),
    ("cp", "Component Pascal"),
    ("cplint", "cplint"),
    ("cpp", "C++"),
    ("cpp-objdump", "cpp-objdump"),
    ("cpsa", "CPSA"),
    ("cr", "Crystal"),
    ("crmsh", "Crmsh"),
    ("croc", "Croc"),
    ("cry", "Cryptol"),
    ("cryptol", "Cryptol"),
    ("crystal", "Crystal"),
    ("cs", "C#"),
    ("csh", "Tcsh"),
    ("csharp", "C#"),
    ("csound", "Csound Orchestra"),
    ("csound-csd", "Csound Document"),
    ("csound-document", "Csound Document"),
    ("csound-orc", "Csound Orchestra"),
    ("csound-sco", "Csound Score"),
    ("csound-score", "Csound Score"),
    ("css", "CSS"),
    ("css+django", "CSS+Django/Jinja"),
    ("css+erb", "CSS+Ruby"),
    ("css+genshi", "CSS+Genshi Text"),
    ("css+genshitext", "CSS+Genshi Text"),
    ("css+jinja", "CSS+Django/Jinja"),
    ("css+lasso", "CSS+Lasso"),
    ("css+mako", "CSS+Mako"),
    ("css+mozpreproc", "CSS+mozpreproc"),
    ("css+myghty", "CSS+Myghty"),
    ("css+php", "CSS+PHP"),
    ("css+ruby", "CSS+Ruby"),
    ("css+smarty", "CSS+Smarty"),
    ("css+ul4", "CSS+UL4"),
    ("cu", "CUDA"),
    ("cucumber", "Gherkin"),
    ("cuda", "CUDA"),
    ("cxx-objdump", "cpp-objdump"),
    ("cypher", "Cypher"),
    ("cython", "Cython"),
    ("d", "D"),
    ("d-objdump", "d-objdump"),
    ("dart", "Dart"),
    ("dasm16", "DASM16"),
    ("dax", "Dax"),
    ("debcontrol", "Debian Control file"),
    ("debian.sources", "Debian Sources file"),
    ("debsources", "Debian Sourcelist"),
    ("delphi", "Delphi"),
    ("desktop", "Desktop file"),
    ("devicetree", "Devicetree"),
    ("dg", "dg"),
    ("diff", "Diff"),
    ("django", "Django/Jinja"),
    ("dmesg", "Kernel log"),
    ("do", "Stata"),
    ("docker", "Docker"),
    ("dockerfile", "Docker"),
    ("dosbatch", "Batchfile"),
    ("doscon", "MSDOS Session"),
    ("dosini", "INI"),
    ("dot", "Graphviz"),
    ("dpatch", "Darcs Patch"),
    ("dtd", "DTD"),
    ("dts", "Devicetree"),
    ("duby", "Ruby"),
    ("duel", "Duel"),
    ("dylan", "Dylan"),
    ("dylan-console", "Dylan session"),
    ("dylan-lid", "DylanLID"),
    ("dylan-repl", "Dylan session"),
    ("earl-grey", "Earl Grey"),
    ("earlgrey", "Earl Grey"),
    ("easytrieve", "Easytrieve"),
    ("ebnf", "EBNF"),
    ("ec", "eC"),
    ("ecl", "ECL"),
    ("eg", "Earl Grey"),
    ("eiffel", "Eiffel"),
    ("elisp", "EmacsLisp"),
    ("elixir", "Elixir"),
    ("elm", "Elm"),
    ("elpi", "Elpi"),
    ("emacs", "EmacsLisp"),
    ("emacs-lisp", "EmacsLisp"),
    ("email", "E-mail"),
    ("eml", "E-mail"),
    ("erb", "ERB"),
    ("erl", "Erlang erl session"),
    ("erlang", "Erlang"),
    ("evoque", "Evoque"),
    ("ex", "Elixir"),
    ("execline", "execline"),
    ("exs", "Elixir"),
    ("extempore", "xtlang"),
    ("ezhil", "Ezhil"),
    ("f#", "F#"),
    ("f90", "Fortran"),
    ("factor", "Factor"),
    ("fan", "Fantom"),
    ("fancy", "Fancy"),
    ("fc", "FunC"),
    ("felix", "Felix"),
    ("fennel", "Fennel"),
    ("fif", "Fift"),
    ("fift", "Fift"),
    ("fish", "Fish"),
    ("fishshell", "Fish"),
    ("flatline", "Flatline"),
    ("flo", "FloScript"),
    ("floscript", "FloScript"),
    ("flx", "Felix"),
    ("fnl", "Fennel"),
    ("forth", "Forth"),
    ("fortran", "Fortran"),
    ("fortranfixed", "FortranFixed"),
    ("foxpro", "FoxPro"),
    ("freefem", "Freefem"),
    ("fsharp", "F#"),
    ("fstar", "FStar"),
    ("func", "FunC"),
    ("futhark", "Futhark"),
    ("fy", "Fancy"),
    ("gap", "GAP"),
    ("gap-console", "GAP session"),
    ("gap-repl", "GAP session"),
    ("gas", "GAS"),
    ("gawk", "Awk"),
    ("gcode", "g-code"),
    ("gd", "GDScript"),
    ("gdscript", "GDScript"),
    ("genshi", "Genshi"),
    ("genshitext", "Genshi Text"),
    ("gherkin", "Gherkin"),
    ("gleam", "Gleam"),
    ("glsl", "GLSL"),
    ("gnuplot", "Gnuplot"),
    ("go", "Go"),
    ("golang", "Go"),
    ("golo", "Golo"),
    ("gooddata-cl", "GoodData-CL"),
    ("googlesql", "GoogleSQL"),
    ("gosu", "Gosu"),
    ("graphql", "GraphQL"),
    ("graphviz", "Graphviz"),
    ("groff", "Groff"),
    ("groovy", "Groovy"),
    ("gsed", "Sed"),
    ("gsql", "GSQL"),
    ("gst", "Gosu Template"),
    ("haml", "Haml"),
    ("handlebars", "Handlebars"),
    ("hare", "Hare"),
    ("haskell", "Haskell"),
    ("haxe", "Haxe"),
    ("haxeml", "Hxml"),
    ("hcl", "Terraform"),
    ("hexdump", "Hexdump"),
    ("hlsl", "HLSL"),
    ("hs", "Haskell"),
    ("hsa", "HSAIL"),
    ("hsail", "HSAIL"),
    ("hspec", "Hspec"),
    ("html", "HTML"),
    ("html+cheetah", "HTML+Cheetah"),
    ("html+django", "HTML+Django/Jinja"),
    ("html+erb", "RHTML"),
    ("html+evoque", "HTML+Evoque"),
    ("html+genshi", "HTML+Genshi"),
    ("html+handlebars", "HTML+Handlebars"),
    ("html+jinja", "HTML+Django/Jinja"),
    ("html+kid", "HTML+Genshi"),
    ("html+lasso", "HTML+Lasso"),
    ("html+mako", "HTML+Mako"),
    ("html+myghty", "HTML+Myghty"),
    ("html+ng2", "HTML + Angular2"),
    ("html+php", "HTML+PHP"),
    ("html+ruby", "RHTML"),
    ("html+smarty", "HTML+Smarty"),
    ("html+spitfire", "HTML+Cheetah"),
    ("html+twig", "HTML+Twig"),
    ("html+ul4", "HTML+UL4"),
    ("html+velocity", "HTML+Velocity"),
    ("htmlcheetah", "HTML+Cheetah"),
    ("htmldjango", "HTML+Django/Jinja"),
    ("http", "HTTP"),
    ("hx", "Haxe"),
    ("hxml", "Hxml"),
    ("hxsl", "Haxe"),
    ("hy", "Hy"),
    ("hybris", "Hybris"),
    ("hylang", "Hy"),
    ("i6", "Inform 6"),
    ("i6t", "Inform 6 template"),
    ("i7", "Inform 7"),
    ("icon", "Icon"),
    ("idl", "IDL"),
    ("idl4", "CAmkES"),
    ("idr", "Idris"),
    ("idris", "Idris"),
    ("iex", "Elixir iex session"),
    ("igor", "Igor"),
    ("igorpro", "Igor"),
    ("ik", "Ioke"),
    ("inform6", "Inform 6"),
    ("inform7", "Inform 7"),
    ("ini", "INI"),
    ("io", "Io"),
    ("ioke", "Ioke"),
    ("irb", "Ruby irb session"),
    ("irc", "IRC logs"),
    ("isabelle", "Isabelle"),
    ("j", "J"),
    ("jade", "Pug"),
    ("jags", "JAGS"),
    ("janet", "Janet"),
    ("jasmin", "Jasmin"),
    ("jasminxt", "Jasmin"),
    ("java", "Java"),
    ("javascript", "JavaScript"),
    ("javascript+cheetah", "JavaScript+Cheetah"),
    ("javascript+django", "JavaScript+Django/Jinja"),
    ("javascript+erb", "JavaScript+Ruby"),
    ("javascript+genshi", "JavaScript+Genshi Text"),
    ("javascript+genshitext", "JavaScript+Genshi Text"),
    ("javascript+jinja", "JavaScript+Django/Jinja"),
    ("javascript+lasso", "JavaScript+Lasso"),
    ("javascript+mako", "JavaScript+Mako"),
    ("javascript+mozpreproc", "Javascript+mozpreproc"),
    ("javascript+myghty", "JavaScript+Myghty"),
    ("javascript+php", "JavaScript+PHP"),
    ("javascript+ruby", "JavaScript+Ruby"),
    ("javascript+smarty", "JavaScript+Smarty"),
    ("javascript+spitfire", "JavaScript+Cheetah"),
    ("jbst", "Duel"),
    ("jcl", "JCL"),
    ("jinja", "Django/Jinja"),
    ("jl", "Julia"),
    ("jlcon", "Julia console"),
    ("jmespath", "JMESPath"),
    ("jp", "JMESPath"),
    ("jproperties", "Properties"),
    ("js", "JavaScript"),
    ("js+cheetah", "JavaScript+Cheetah"),
    ("js+django", "JavaScript+Django/Jinja"),
    ("js+erb", "JavaScript+Ruby"),
    ("js+genshi", "JavaScript+Genshi Text"),
    ("js+genshitext", "JavaScript+Genshi Text"),
    ("js+jinja", "JavaScript+Django/Jinja"),
    ("js+lasso", "JavaScript+Lasso"),
    ("js+mako", "JavaScript+Mako"),
    ("js+myghty", "JavaScript+Myghty"),
    ("js+php", "JavaScript+PHP"),
    ("js+ruby", "JavaScript+Ruby"),
    ("js+smarty", "JavaScript+Smarty"),
    ("js+spitfire", "JavaScript+Cheetah"),
    ("js+ul4", "Javascript+UL4"),
    ("jsgf", "JSGF"),
    ("jslt", "JSLT"),
    ("json", "JSON"),
    ("json-ld", "JSON-LD"),
    ("json-object", "JSON"),
    ("json5", "JSON5"),
    ("jsonld", "JSON-LD"),
    ("jsonml+bst", "Duel"),
    ("jsonnet", "Jsonnet"),
    ("jsp", "Java Server Page"),
    ("jsx", "JSX"),
    ("julia", "Julia"),
    ("julia-repl", "Julia console"),
    ("juttle", "Juttle"),
    ("k", "K"),
    ("kal", "Kal"),
    ("kconfig", "Kconfig"),
    ("kernel-config", "Kconfig"),
    ("kid", "Genshi"),
    ("kmsg", "Kernel log"),
    ("koka", "Koka"),
    ("kotlin", "Kotlin"),
    ("kql", "Kusto"),
    ("ksh", "Bash"),
    ("kuin", "Kuin"),
    ("kusto", "Kusto"),
    ("lagda", "Literate Agda"),
    ("lasso", "Lasso"),
    ("lassoscript", "Lasso"),
    ("latex", "TeX"),
    ("lcry", "Literate Cryptol"),
    ("lcryptol", "Literate Cryptol"),
    ("ldapconf", "LDAP configuration file"),
    ("ldaprc", "LDAP configuration file"),
    ("ldif", "LDIF"),
    ("lean", "Lean"),
    ("lean3", "Lean"),
    ("lean4", "Lean4"),
    ("less", "LessCss"),
    ("lhaskell", "Literate Haskell"),
    ("lhs", "Literate Haskell"),
    ("lid", "DylanLID"),
    ("lidr", "Literate Idris"),
    ("lidris", "Literate Idris"),
    ("lighttpd", "Lighttpd configuration file"),
    ("lighty", "Lighttpd configuration file"),
    ("lilypond", "LilyPond"),
    ("limbo", "Limbo"),
    ("linux-config", "Kconfig"),
    ("linuxconfig", "Unix/Linux config files"),
    ("liquid", "liquid"),
    ("lisp", "Common Lisp"),
    ("literate-agda", "Literate Agda"),
    ("literate-cryptol", "Literate Cryptol"),
    ("literate-haskell", "Literate Haskell"),
    ("literate-idris", "Literate Idris"),
    ("live-script", "LiveScript"),
    ("livescript", "LiveScript"),
    ("llvm", "LLVM"),
    ("llvm-mir", "LLVM-MIR"),
    ("llvm-mir-body", "LLVM-MIR Body"),
    ("lobas", "VB.net"),
    ("logos", "Logos"),
    ("logtalk", "Logtalk"),
    ("lsl", "LSL"),
    ("lua", "Lua"),
    ("luau", "Luau"),
    ("m2", "Modula-2"),
    ("macaulay2", "Macaulay2"),
    ("macsyma", "Maxima"),
    ("make", "Makefile"),
    ("makefile", "Makefile"),
    ("mako", "Mako"),
    ("man", "Groff"),
    ("maple", "Maple"),
    ("maql", "MAQL"),
    ("markdown", "Markdown"),
    ("mask", "Mask"),
    ("mason", "Mason"),
    ("mathematica", "Mathematica"),
    ("matlab", "Matlab"),
    ("matlabsession", "Matlab session"),
    ("mawk", "Awk"),
    ("maxima", "Maxima"),
    ("mcf", "MCFunction"),
    ("mcfunction", "MCFunction"),
    ("mcschema", "MCSchema"),
    ("md", "Markdown"),
    ("mediawiki", "Wikitext"),
    ("menuconfig", "Kconfig"),
    ("meson", "Meson"),
    ("meson.build", "Meson"),
    ("mf", "Makefile"),
    ("mime", "MIME"),
    ("minid", "MiniD"),
    ("miniscript", "MiniScript"),
    ("mips", "MIPS"),
    ("mma", "Mathematica"),
    ("modelica", "Modelica"),
    ("modula2", "Modula-2"),
    ("moin", "MoinMoin/Trac Wiki markup"),
    ("mojo", "Mojo"),
    ("monkey", "Monkey"),
    ("monte", "Monte"),
    ("moo", "MOOCode"),
    ("moocode", "MOOCode"),
    ("moon", "MoonScript"),
    ("moonscript", "MoonScript"),
    ("mosel", "Mosel"),
    ("mozhashpreproc", "mozhashpreproc"),
    ("mozpercentpreproc", "mozpercentpreproc"),
    ("mq4", "MQL"),
    ("mq5", "MQL"),
    ("mql", "MQL"),
    ("mql4", "MQL"),
    ("mql5", "MQL"),
    ("ms", "MiniScript"),
    ("msc", "Mscgen"),
    ("mscgen", "Mscgen"),
    ("mupad", "MuPAD"),
    ("mxml", "MXML"),
    ("myghty", "Myghty"),
    ("mysql", "MySQL"),
    ("nasm", "NASM"),
    ("nawk", "Awk"),
    ("nb", "Mathematica"),
    ("ncl", "NCL"),
    ("nemerle", "Nemerle"),
    ("nesc", "nesC"),
    ("nestedtext", "NestedText"),
    ("newlisp", "NewLisp"),
    ("newspeak", "Newspeak"),
    ("ng2", "Angular2"),
    ("nginx", "Nginx configuration file"),
    ("nim", "Nimrod"),
    ("nimrod", "Nimrod"),
    ("nit", "Nit"),
    ("nix", "Nix"),
    ("nixos", "Nix"),
    ("nodejsrepl", "Node.js REPL console session"),
    ("notmuch", "Notmuch"),
    ("nroff", "Groff"),
    ("nsh", "NSIS"),
    ("nsi", "NSIS"),
    ("nsis", "NSIS"),
    ("nt", "NestedText"),
    ("numba_ir", "Numba_IR"),
    ("numbair", "Numba_IR"),
    ("numpy", "NumPy"),
    ("nusmv", "NuSMV"),
    ("obj-c", "Objective-C"),
    ("obj-c++", "Objective-C++"),
    ("obj-j", "Objective-J"),
    ("objc", "Objective-C"),
    ("objc++", "Objective-C++"),
    ("objdump", "objdump"),
    ("objdump-nasm", "objdump-nasm"),
    ("objective-c", "Objective-C"),
    ("objective-c++", "Objective-C++"),
    ("objective-j", "Objective-J"),
    ("objectivec", "Objective-C"),
    ("objectivec++", "Objective-C++"),
    ("objectivej", "Objective-J"),
    ("objectpascal", "Delphi"),
    ("objj", "Objective-J"),
    ("ocaml", "OCaml"),
    ("octave", "Octave"),
    ("odin", "ODIN"),
    ("omg-idl", "OMG Interface Definition Language"),
    ("oobas", "VB.net"),
    ("ooc", "Ooc"),
    ("opa", "Opa"),
    ("openbugs", "BUGS"),
    ("openedge", "OpenEdge ABL"),
    ("openrc", "Bash"),
    ("openscad", "OpenSCAD"),
    ("org", "Org Mode"),
    ("org-mode", "Org Mode"),
    ("orgmode", "Org Mode"),
    ("output", "Text output"),
    ("pacmanconf", "PacmanConf"),
    ("pan", "Pan"),
    ("parasail", "ParaSail"),
    ("pas", "Delphi"),
    ("pascal", "Delphi"),
    ("pawn", "Pawn"),
    ("pcmk", "Crmsh"),
    ("pddl", "PDDL"),
    ("peg", "PEG"),
    ("pem", "ASCII armored"),
    ("perl", "Perl"),
    ("perl6", "Perl6"),
    ("phix", "Phix"),
    ("php", "PHP"),
    ("php3", "PHP"),
    ("php4", "PHP"),
    ("php5", "PHP"),
    ("pig", "Pig"),
    ("pike", "Pike"),
    ("pkgconfig", "PkgConfig"),
    ("pl", "Perl"),
    ("pl6", "Perl6"),
    ("plpgsql", "PL/pgSQL"),
    ("po", "Gettext Catalog"),
    ("pointless", "Pointless"),
    ("pony", "Pony"),
    ("portugol", "Portugol"),
    ("posh", "PowerShell"),
    ("postgres", "PostgreSQL SQL dialect"),
    ("postgres-console", "PostgreSQL console (psql)"),
    ("postgres-explain", "PostgreSQL EXPLAIN dialect"),
    ("postgresql", "PostgreSQL SQL dialect"),
    ("postgresql-console", "PostgreSQL console (psql)"),
    ("postscr", "PostScript"),
    ("postscript", "PostScript"),
    ("pot", "Gettext Catalog"),
    ("pov", "POVRay"),
    ("powershell", "PowerShell"),
    ("praat", "Praat"),
    ("procfile", "Procfile"),
    ("progress", "OpenEdge ABL"),
    ("prolog", "Prolog"),
    ("promela", "Promela"),
    ("promql", "PromQL"),
    ("properties", "Properties"),
    ("proto", "Protocol Buffer"),
    ("protobuf", "Protocol Buffer"),
    ("prql", "PRQL"),
    ("ps1", "PowerShell"),
    ("ps1con", "PowerShell Session"),
    ("psm1", "PowerShell"),
    ("psql", "PostgreSQL console (psql)"),
    ("psysh", "PsySH console session for PHP"),
    ("ptx", "PTX"),
    ("pug", "Pug"),
    ("puppet", "Puppet"),
    ("pwsh", "PowerShell"),
    ("pwsh-session", "PowerShell Session"),
    ("py", "Python"),
    ("py+ul4", "Python+UL4"),
    ("py2", "Python 2.x"),
    ("py2tb", "Python 2.x Traceback"),
    ("py3", "Python"),
    ("py3tb", "Python Traceback"),
    ("pycon", "Python console session"),
    ("pyi", "Python"),
    ("pypy", "PyPy Log"),
    ("pypylog", "PyPy Log"),
    ("pyrex", "Cython"),
    ("pytb", "Python Traceback"),
    ("python", "Python"),
    ("python-console", "Python console session"),
    ("python2", "Python 2.x"),
    ("python3", "Python"),
    ("pyx", "Cython"),
    ("q", "Q"),
    ("qbasic", "QBasic"),
    ("qbs", "QML"),
    ("ql", "CodeQL"),
    ("qlik", "Qlik"),
    ("qlikscript", "Qlik"),
    ("qliksense", "Qlik"),
    ("qlikview", "Qlik"),
    ("qml", "QML"),
    ("qvt", "QVTO"),
    ("qvto", "QVTO"),
    ("r", "S"),
    ("racket", "Racket"),
    ("ragel", "Ragel"),
    ("ragel-c", "Ragel in C Host"),
    ("ragel-cpp", "Ragel in CPP Host"),
    ("ragel-d", "Ragel in D Host"),
    ("ragel-em", "Embedded Ragel"),
    ("ragel-java", "Ragel in Java Host"),
    ("ragel-objc", "Ragel in Objective C Host"),
    ("ragel-rb", "Ragel in Ruby Host"),
    ("ragel-ruby", "Ragel in Ruby Host"),
    ("raku", "Perl6"),
    ("rb", "Ruby"),
    ("rbcon", "Ruby irb session"),
    ("rconsole", "RConsole"),
    ("rd", "Rd"),
    ("react", "JSX"),
    ("reason", "ReasonML"),
    ("reasonml", "ReasonML"),
    ("rebol", "REBOL"),
    ("red", "Red"),
    ("red/system", "Red"),
    ("redcode", "Redcode"),
    ("registry", "reg"),
    ("rego", "Rego"),
    ("resource", "ResourceBundle"),
    ("resourcebundle", "ResourceBundle"),
    ("rest", "reStructuredText"),
    ("restructuredtext", "reStructuredText"),
    ("rexx", "Rexx"),
    ("rhtml", "RHTML"),
    ("ride", "Ride"),
    ("rita", "Rita"),
    ("rkt", "Racket"),
    ("rnc", "Relax-NG Compact"),
    ("rng-compact", "Relax-NG Compact"),
    ("roboconf-graph", "Roboconf Graph"),
    ("roboconf-instances", "Roboconf Instances"),
    ("robotframework", "RobotFramework"),
    ("rout", "RConsole"),
    ("rql", "RQL"),
    ("rs", "Rust"),
    ("rsl", "RSL"),
    ("rst", "reStructuredText"),
    ("rts", "TrafficScript"),
    ("ruby", "Ruby"),
    ("rust", "Rust"),
    ("s", "S"),
    ("sage", "Python"),
    ("salt", "YAML+Jinja"),
    ("sarl", "SARL"),
    ("sas", "SAS"),
    ("sass", "Sass"),
    ("savi", "Savi"),
    ("sbatch", "Slurm"),
    ("sc", "SuperCollider"),
    ("scala", "Scala"),
    ("scaml", "Scaml"),
    ("scd", "scdoc"),
    ("scdoc", "scdoc"),
    ("scheme", "Scheme"),
    ("scilab", "Scilab"),
    ("scm", "Scheme"),
    ("scss", "SCSS"),
    ("sed", "Sed"),
    ("sgf", "SmartGameFormat"),
    ("sh", "Bash"),
    ("shell", "Bash"),
    ("shell-session", "Bash Session"),
    ("shen", "Shen"),
    ("shex", "ShExC"),
    ("shexc", "ShExC"),
    ("sieve", "Sieve"),
    ("silver", "Silver"),
    ("singularity", "Singularity"),
    ("slash", "Slash"),
    ("slim", "Slim"),
    ("sls", "YAML+Jinja"),
    ("slurm", "Slurm"),
    ("smali", "Smali"),
    ("smalltalk", "Smalltalk"),
    ("smarty", "Smarty"),
    ("smithy", "Smithy"),
    ("sml", "Standard ML"),
    ("snbt", "SNBT"),
    ("snobol", "Snobol"),
    ("snowball", "Snowball"),
    ("sobas", "VB.net"),
    ("solidity", "Solidity"),
    ("soong", "Soong"),
    ("sophia", "Sophia"),
    ("sources.list", "Debian Sourcelist"),
    ("sourceslist", "Debian Sourcelist"),
    ("sp", "SourcePawn"),
    ("sparql", "SPARQL"),
    ("spec", "RPMSpec"),
    ("spice", "Spice"),
    ("spicelang", "Spice"),
    ("spitfire", "Cheetah"),
    ("splus", "S"),
    ("sql", "SQL"),
    ("sql+jinja", "SQL+Jinja"),
    ("sqlite3", "sqlite3con"),
    ("squeak", "Smalltalk"),
    ("squid", "SquidConf"),
    ("squid.conf", "SquidConf"),
    ("squidconf", "SquidConf"),
    ("srcinfo", "Srcinfo"),
    ("ssed", "Sed"),
    ("ssp", "Scalate Server Page"),
    ("st", "Smalltalk"),
    ("stan", "Stan"),
    ("starlark", "Python"),
    ("stata", "Stata"),
    ("supercollider", "SuperCollider"),
    ("sv", "systemverilog"),
    ("swift", "Swift"),
    ("swig", "SWIG"),
    ("systemd", "Systemd"),
    ("systemverilog", "systemverilog"),
    ("t-sql", "Transact-SQL"),
    ("tablegen", "TableGen"),
    ("tact", "Tact"),
    ("tads3", "TADS 3"),
    ("tal", "Tal"),
    ("tap", "TAP"),
    ("tasm", "TASM"),
    ("tcl", "Tcl"),
    ("tcsh", "Tcsh"),
    ("tcshcon", "Tcsh Session"),
    ("td", "TableGen"),
    ("tea", "Tea"),
    ("teal", "teal"),
    ("teraterm", "Tera Term macro"),
    ("teratermmacro", "Tera Term macro"),
    ("termcap", "Termcap"),
    ("terminfo", "Terminfo"),
    ("terraform", "Terraform"),
    ("tex", "TeX"),
    ("text", "Text only"),
    ("tf", "Terraform"),
    ("thingsdb", "ThingsDB"),
    ("thrift", "Thrift"),
    ("ti", "ThingsDB"),
    ("tid", "tiddler"),
    ("tlb", "Tl-b"),
    ("tls", "TLS Presentation Language"),
    ("tnt", "Typographic Number Theory"),
    ("todotxt", "Todotxt"),
    ("toml", "TOML"),
    ("trac-wiki", "MoinMoin/Trac Wiki markup"),
    ("trafficscript", "TrafficScript"),
    ("treetop", "Treetop"),
    ("ts", "TypeScript"),
    ("tsql", "Transact-SQL"),
    ("tsx", "TSX"),
    ("ttl", "Tera Term macro"),
    ("turtle", "Turtle"),
    ("twig", "Twig"),
    ("typescript", "TypeScript"),
    ("typoscript", "TypoScript"),
    ("typoscriptcssdata", "TypoScriptCssData"),
    ("typoscripthtmldata", "TypoScriptHtmlData"),
    ("typst", "Typst"),
    ("ucode", "ucode"),
    ("udiff", "Diff"),
    ("ul4", "UL4"),
    ("unicon", "Unicon"),
    ("unixconfig", "Unix/Linux config files"),
    ("urbiscript", "UrbiScript"),
    ("urlencoded", "urlencoded"),
    ("usd", "USD"),
    ("usda", "USD"),
    ("uxntal", "Tal"),
    ("v", "verilog"),
    ("vala", "Vala"),
    ("vapi", "Vala"),
    ("vb.net", "VB.net"),
    ("vbnet", "VB.net"),
    ("vbscript", "VBScript"),
    ("vcl", "VCL"),
    ("vclsnippet", "VCLSnippets"),
    ("vclsnippets", "VCLSnippets"),
    ("vctreestatus", "VCTreeStatus"),
    ("velocity", "Velocity"),
    ("verifpal", "Verifpal"),
    ("verilog", "verilog"),
    ("vfp", "FoxPro"),
    ("vgl", "VGL"),
    ("vhdl", "vhdl"),
    ("vim", "VimL"),
    ("visual-basic", "VB.net"),
    ("visualbasic", "VB.net"),
    ("visualprolog", "Visual Prolog"),
    ("visualprologgrammar", "Visual Prolog Grammar"),
    ("vue", "Vue"),
    ("vyper", "Vyper"),
    ("wast", "WebAssembly"),
    ("wat", "WebAssembly"),
    ("wdiff", "WDiff"),
    ("webidl", "Web IDL"),
    ("wgsl", "WebGPU Shading Language"),
    ("whiley", "Whiley"),
    ("wikitext", "Wikitext"),
    ("winbatch", "Batchfile"),
    ("winbugs", "BUGS"),
    ("wowtoc", "World of Warcraft TOC"),
    ("wren", "Wren"),
    ("x++", "X++"),
    ("x10", "X10"),
    ("xbase", "FoxPro"),
    ("xml", "XML"),
    ("xml+cheetah", "XML+Cheetah"),
    ("xml+django", "XML+Django/Jinja"),
    ("xml+erb", "XML+Ruby"),
    ("xml+evoque", "XML+Evoque"),
    ("xml+genshi", "Genshi"),
    ("xml+jinja", "XML+Django/Jinja"),
    ("xml+kid", "Genshi"),
    ("xml+lasso", "XML+Lasso"),
    ("xml+mako", "XML+Mako"),
    ("xml+myghty", "XML+Myghty"),
    ("xml+php", "XML+PHP"),
    ("xml+ruby", "XML+Ruby"),
    ("xml+smarty", "XML+Smarty"),
    ("xml+spitfire", "XML+Cheetah"),
    ("xml+ul4", "XML+UL4"),
    ("xml+velocity", "XML+Velocity"),
    ("xorg.conf", "Xorg"),
    ("xpp", "X++"),
    ("xq", "XQuery"),
    ("xql", "XQuery"),
    ("xqm", "XQuery"),
    ("xquery", "XQuery"),
    ("xqy", "XQuery"),
    ("xslt", "XSLT"),
    ("xten", "X10"),
    ("xtend", "Xtend"),
    ("xul+mozpreproc", "XUL+mozpreproc"),
    ("yaml", "YAML"),
    ("yaml+jinja", "YAML+Jinja"),
    ("yang", "YANG"),
    ("yar", "YARA"),
    ("yara", "YARA"),
    ("zeek", "Zeek"),
    ("zephir", "Zephir"),
    ("zetasql", "GoogleSQL"),
    ("zig", "Zig"),
    ("zone", "Zone"),
    ("zsh", "Bash"),
    ("🔥", "Mojo"),
];

/// The lexer a fence tag resolves to, or `None` when Pygments knows no such name.
///
/// Case-insensitive, because `get_lexer_by_name` compares lowercased aliases.
///
/// ```
/// use _native::syntax_lexers::lexer_for_tag;
/// assert_eq!(lexer_for_tag("typescript"), Some("TypeScript"));
/// assert_eq!(lexer_for_tag("TS"), Some("TypeScript"));
/// assert_eq!(lexer_for_tag("text"), Some("Text only"));
/// // No lexer at all — the product renders these plain.
/// assert_eq!(lexer_for_tag("mermaid"), None);
/// assert_eq!(lexer_for_tag(""), None);
/// ```
pub fn lexer_for_tag(tag: &str) -> Option<&'static str> {
    let lowered = tag.to_lowercase();
    LEXER_ALIASES
        .binary_search_by(|(alias, _)| alias.cmp(&lowered.as_str()))
        .ok()
        .map(|index| LEXER_ALIASES[index].1)
}
