//! Which file names a `Read` result's highlight resolves to a promoted family.
//!
//! Generated by
//! `teammates/cutover-finisher/probes/generate_read_lexers.py`. Do not edit.
//!
//! Every glob here has exactly one Pygments candidate unless `conditional` is
//! set, in which case a template delegate can take the file away from the
//! promoted lexer and `session_render` runs the delegation test.

/// `(glob, promoted display name, rule)`, sorted. The rule is
/// `unconditional`, or the name of a content test `session_render` runs.
pub const READ_PROMOTED_FILENAMES: &[(&str, &str, &str)] = &[
    ("*.bash", "Bash", "unconditional"),
    ("*.bzl", "Python", "unconditional"),
    ("*.cjs", "JavaScript", "unconditional"),
    ("*.ebuild", "Bash", "unconditional"),
    ("*.eclass", "Bash", "unconditional"),
    ("*.exheres-0", "Bash", "unconditional"),
    ("*.exlib", "Bash", "unconditional"),
    ("*.js", "JavaScript", "js-delegates"),
    ("*.jsm", "JavaScript", "unconditional"),
    ("*.json", "JSON", "unconditional"),
    ("*.jsonl", "JSON", "unconditional"),
    ("*.jy", "Python", "unconditional"),
    ("*.ksh", "Bash", "unconditional"),
    ("*.mjs", "JavaScript", "unconditional"),
    ("*.ndjson", "JSON", "unconditional"),
    ("*.py", "Python", "unconditional"),
    ("*.pyi", "Python", "unconditional"),
    ("*.pyw", "Python", "unconditional"),
    ("*.sage", "Python", "unconditional"),
    ("*.sc", "Python", "python-shebang"),
    ("*.sh", "Bash", "unconditional"),
    ("*.tac", "Python", "unconditional"),
    ("*.ts", "TypeScript", "unconditional"),
    ("*.tsx", "TSX", "unconditional"),
    ("*.zsh", "Bash", "unconditional"),
    (".bash_*", "Bash", "unconditional"),
    (".bashrc", "Bash", "unconditional"),
    (".kshrc", "Bash", "unconditional"),
    (".zshrc", "Bash", "unconditional"),
    ("BUCK", "Python", "unconditional"),
    ("BUILD", "Python", "unconditional"),
    ("BUILD.bazel", "Python", "unconditional"),
    ("PKGBUILD", "Bash", "unconditional"),
    ("Pipfile.lock", "JSON", "unconditional"),
    ("SConscript", "Python", "unconditional"),
    ("SConstruct", "Python", "unconditional"),
    ("WORKSPACE", "Python", "unconditional"),
    ("bash_*", "Bash", "unconditional"),
    ("bashrc", "Bash", "unconditional"),
    ("kshrc", "Bash", "unconditional"),
    ("zshrc", "Bash", "unconditional"),
];
