//! Argv parsing for `ch search`.
//!
//! Truth is CPython `argparse` as configured in `src/chats/cli.py`, including
//! its positional repairs and its exact error bytes. Usage text is generated by
//! the sibling formatter rather than stored, because argparse rewraps it to the
//! terminal width.

//! Search argument grammar: argparse-faithful parsing for `ch search ...`.
//!
//! Byte-exact help and error surfaces are pinned by the cycle-03 contract
//! fixtures; the parse order mirrors `src/chats/cli.py` exactly (unknown
//! arguments, repair, required pattern, mode forcing, role normalization,
//! then value resolvers).
//!
//! Temporary allowance: execution fields stay unread until the query-engine
//! and confirmation slices land.

#![allow(dead_code)]

use std::ffi::OsString;
use std::io::IsTerminal;

use crate::inventory::Provider;
use crate::shortening::{ShortPolicy, looks_like_short_spec};
use crate::tool_filter::ToolVisibility;
use crate::visibility::{ConversationFlags, MessageSelection};



#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SearchOutputMode {
    Matches,
    List,
    Full,
    OnlyId,
}

#[derive(Clone, Debug)]
pub struct SearchPoolFilter {
    pub directory: Option<String>,
    pub modified_after: Option<String>,
    pub created_after: Option<String>,
    pub provider: Option<Provider>,
}

#[derive(Clone, Debug)]
pub struct SearchArguments {
    pub pattern: String,
    pub case_sensitive: bool,
    pub output_mode: SearchOutputMode,
    pub raw_output: bool,
    pub emit_metadata: bool,
    pub flags: ConversationFlags,
    pub pool_filter: SearchPoolFilter,
}

#[derive(Debug)]
pub enum SearchOutcome {
    Help,
    Error(String),
    Run(Box<SearchArguments>),
}

#[derive(Debug)]
pub struct ParsedSearch {
    pub warnings: Vec<String>,
    pub outcome: SearchOutcome,
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum Arity {
    Flag,
    Required,
    Optional,
}

#[derive(Clone, Copy)]
struct LongSpec {
    name: &'static str,
    arity: Arity,
}

const LONG_OPTIONS: &[LongSpec] = &[
    LongSpec { name: "--help", arity: Arity::Flag },
    LongSpec { name: "--list", arity: Arity::Flag },
    LongSpec { name: "--only-id", arity: Arity::Flag },
    LongSpec { name: "--full", arity: Arity::Flag },
    LongSpec { name: "--raw", arity: Arity::Flag },
    LongSpec { name: "--dir", arity: Arity::Required },
    LongSpec { name: "--mafter", arity: Arity::Required },
    LongSpec { name: "--cafter", arity: Arity::Required },
    LongSpec { name: "--provider", arity: Arity::Required },
    LongSpec { name: "--thinking", arity: Arity::Optional },
    LongSpec { name: "--only-user", arity: Arity::Flag },
    LongSpec { name: "--only-assistant", arity: Arity::Flag },
    LongSpec { name: "--tools", arity: Arity::Optional },
    LongSpec { name: "--agents", arity: Arity::Flag },
    LongSpec { name: "--branches", arity: Arity::Flag },
    LongSpec { name: "--all", arity: Arity::Flag },
    LongSpec { name: "--plans", arity: Arity::Flag },
    LongSpec { name: "--case-sensitive", arity: Arity::Flag },
    LongSpec { name: "--case-insensitive", arity: Arity::Flag },
    LongSpec { name: "--short", arity: Arity::Optional },
    LongSpec { name: "--color", arity: Arity::Required },
    LongSpec { name: "--paging", arity: Arity::Flag },
    LongSpec { name: "--no-paging", arity: Arity::Flag },
    LongSpec { name: "--no-metadata", arity: Arity::Flag },
];

const SHORT_OPTIONS: &[&str] = &[
    "-h", "-l", "-ll", "-f", "-d", "-ma", "-ca", "-p", "-T", "-t", "-a", "-b", "-A", "-s", "-i",
    "-r",
];

fn short_arity(name: &str) -> Option<Arity> {
    match name {
        "-h" | "-l" | "-ll" | "-f" | "-a" | "-b" | "-A" | "-s" | "-i" | "-r" => Some(Arity::Flag),
        "-d" | "-ma" | "-ca" | "-p" => Some(Arity::Required),
        "-T" | "-t" => Some(Arity::Optional),
        _ => None,
    }
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum CaseSide {
    Sensitive,
    Insensitive,
}

#[derive(Clone, Default)]
struct RawArguments {
    pattern: Option<String>,
    list: bool,
    only_id: bool,
    full: bool,
    raw: bool,
    thinking_present: bool,
    thinking: Option<String>,
    tool_values: Vec<Option<String>>,
    only_user: bool,
    only_assistant: bool,
    agents: bool,
    branches: bool,
    all: bool,
    plans: bool,
    case_side: Option<CaseSide>,
    case_sensitive: bool,
    short_present: bool,
    short_text: Option<String>,
    short_attached: bool,
    color: Option<String>,
    paging: Option<bool>,
    no_metadata: bool,
    directory: Option<String>,
    modified_after: Option<String>,
    created_after: Option<String>,
    provider: Option<Provider>,
    unknown: Vec<String>,
}

impl SearchPoolFilter {
    /// Whether no filter narrows the pool, which picks the no-results wording.
    ///
    /// Python is `not (provider or dir or mafter or cafter)` — **truthiness**, so
    /// an empty string counts as absent. Measured: `-d ""` produces the plain
    /// `No sessions match "x".` while `-d /tmp/g` produces the `with the current
    /// filters` form. Testing `is_none()` alone would give an empty `-d` the
    /// filtered wording.
    ///
    /// Note the same empty string reads differently elsewhere in this struct:
    /// `-ma ""` is *not* absent to the date path, which parses it and raises
    /// `Invalid date format` once per candidate file. One value, two readings,
    /// both deliberate.
    pub fn is_empty(&self) -> bool {
        fn blank(value: &Option<String>) -> bool {
            value.as_deref().unwrap_or_default().is_empty()
        }
        self.provider.is_none()
            && blank(&self.directory)
            && blank(&self.modified_after)
            && blank(&self.created_after)
    }
}

pub fn parse_search_arguments(arguments: &[OsString]) -> ParsedSearch {    let tokens = arguments
        .iter()
        .map(|argument| argument.to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    let mut raw = RawArguments {
        short_attached: tokens
            .iter()
            .any(|token| token.starts_with("--short=") || token.starts_with("-s=")),
        ..RawArguments::default()
    };
    let mut warnings = Vec::new();
    let outcome = parse_tokens(&tokens, &mut raw, &mut warnings);
    ParsedSearch { warnings, outcome }
}

fn parse_tokens(
    tokens: &[String],
    raw: &mut RawArguments,
    warnings: &mut Vec<String>,
) -> SearchOutcome {
    let normalized = match normalize_option_tokens(tokens.to_vec()) {
        Ok(normalized) => normalized,
        Err(error) => return SearchOutcome::Error(error),
    };
    let mut options_enabled = true;
    let mut index = 0;
    while index < normalized.len() {
        let token = &normalized[index];
        if options_enabled && token == "--" {
            options_enabled = false;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-h" | "--help") {
            return SearchOutcome::Help;
        }
        if options_enabled && matches!(token.as_str(), "-l" | "--list") {
            raw.list = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-ll" | "--only-id") {
            raw.only_id = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-f" | "--full") {
            raw.full = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-r" | "--raw") {
            raw.raw = true;
            index += 1;
            continue;
        }
        if options_enabled && token == "--only-user" {
            raw.only_user = true;
            index += 1;
            continue;
        }
        if options_enabled && token == "--only-assistant" {
            raw.only_assistant = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-a" | "--agents") {
            raw.agents = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-b" | "--branches") {
            raw.branches = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-A" | "--all") {
            raw.all = true;
            index += 1;
            continue;
        }
        if options_enabled && token == "--plans" {
            raw.plans = true;
            index += 1;
            continue;
        }
        if options_enabled && token == "--paging" {
            raw.paging = Some(true);
            index += 1;
            continue;
        }
        if options_enabled && token == "--no-paging" {
            raw.paging = Some(false);
            index += 1;
            continue;
        }
        if options_enabled && token == "--no-metadata" {
            raw.no_metadata = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-s" | "--case-sensitive") {
            if let Some(error) = register_case_side(raw, CaseSide::Sensitive, "-s/--case-sensitive", "-i/--case-insensitive") {
                return SearchOutcome::Error(error);
            }
            raw.case_sensitive = true;
            index += 1;
            continue;
        }
        if options_enabled && matches!(token.as_str(), "-i" | "--case-insensitive") {
            if let Some(error) = register_case_side(raw, CaseSide::Insensitive, "-i/--case-insensitive", "-s/--case-sensitive") {
                return SearchOutcome::Error(error);
            }
            raw.case_sensitive = false;
            index += 1;
            continue;
        }
        if options_enabled && option_matches(token, "--dir", &["-d"]) {
            let Some((value, consumed)) = required_value(&normalized, index) else {
                return SearchOutcome::Error(
                    "argument -d/--dir: expected one argument".to_string(),
                );
            };
            raw.directory = Some(value);
            index += consumed;
            continue;
        }
        if options_enabled && option_matches(token, "--mafter", &["-ma"]) {
            let Some((value, consumed)) = required_value(&normalized, index) else {
                return SearchOutcome::Error(
                    "argument -ma/--mafter: expected one argument".to_string(),
                );
            };
            raw.modified_after = Some(value);
            index += consumed;
            continue;
        }
        if options_enabled && option_matches(token, "--cafter", &["-ca"]) {
            let Some((value, consumed)) = required_value(&normalized, index) else {
                return SearchOutcome::Error(
                    "argument -ca/--cafter: expected one argument".to_string(),
                );
            };
            raw.created_after = Some(value);
            index += consumed;
            continue;
        }
        if options_enabled && option_matches(token, "--provider", &["-p"]) {
            let Some((value, consumed)) = required_value(&normalized, index) else {
                return SearchOutcome::Error(
                    "argument -p/--provider: expected one argument".to_string(),
                );
            };
            raw.provider = match value.as_str() {
                "claude" => Some(Provider::Claude),
                "pi" => Some(Provider::Pi),
                "codex" => Some(Provider::Codex),
                other => {
                    return SearchOutcome::Error(format!(
                        "argument -p/--provider: invalid choice: {} \
                         (choose from 'claude', 'pi', 'codex')",
                        python_quoted(other)
                    ));
                }
            };
            index += consumed;
            continue;
        }
        if options_enabled && option_matches(token, "--color", &[]) {
            let Some((value, consumed)) = required_value(&normalized, index) else {
                return SearchOutcome::Error(
                    "argument --color: expected one argument".to_string(),
                );
            };
            if !matches!(value.as_str(), "always" | "never" | "auto") {
                return SearchOutcome::Error(format!(
                    "argument --color: invalid choice: {} \
                     (choose from 'always', 'never', 'auto')",
                    python_quoted(&value)
                ));
            }
            raw.color = Some(value);
            index += consumed;
            continue;
        }
        if options_enabled && optional_option_matches(token, "--thinking", "-T") {
            raw.thinking_present = true;
            let (value, consumed, _) = optional_value(&normalized, index, "-T");
            raw.thinking = value.filter(|value| !value.is_empty()).or(Some("full".to_string()));
            index += consumed;
            continue;
        }
        if options_enabled && optional_option_matches(token, "--tools", "-t") {
            let (value, consumed, _) = optional_value(&normalized, index, "-t");
            raw.tool_values.push(value.filter(|value| !value.is_empty()));
            index += consumed;
            continue;
        }
        if options_enabled && long_optional_matches(token, "--short") {
            raw.short_present = true;
            let (value, consumed, attached) = optional_value(&normalized, index, "--short");
            raw.short_text = value;
            raw.short_attached |= attached;
            index += consumed;
            continue;
        }
        // argparse treats a lone `-` as a positional, by the stdin convention,
        // so it becomes the pattern rather than an unrecognized option.
        if options_enabled
            && token != "-"
            && token.starts_with('-')
            && !is_argparse_negative_number(token)
        {
            raw.unknown.push(token.clone());
            index += 1;
            continue;
        }
        if raw.pattern.is_none() {
            raw.pattern = Some(token.clone());
        } else {
            raw.unknown.push(token.clone());
        }
        index += 1;
    }
    if !raw.unknown.is_empty() {
        return SearchOutcome::Error(format!(
            "unrecognized arguments: {}",
            raw.unknown.join(" ")
        ));
    }
    repair_short_positional(raw);
    let Some(pattern) = raw.pattern.clone() else {
        return SearchOutcome::Error(
            "the following arguments are required: pattern".to_string(),
        );
    };
    finish_arguments(raw.clone(), pattern, warnings)
}

fn register_case_side(
    raw: &mut RawArguments,
    side: CaseSide,
    current: &'static str,
    other: &'static str,
) -> Option<String> {
    if raw.case_side == Some(side) {
        raw.case_sensitive = side == CaseSide::Sensitive;
        return None;
    }
    if raw.case_side.is_some() {
        return Some(format!(
            "argument {current}: not allowed with argument {other}"
        ));
    }
    raw.case_side = Some(side);
    raw.case_sensitive = side == CaseSide::Sensitive;
    None
}

fn finish_arguments(
    mut raw: RawArguments,
    pattern: String,
    warnings: &mut Vec<String>,
) -> SearchOutcome {
    let output_mode = if raw.only_id {
        SearchOutputMode::OnlyId
    } else if raw.list {
        SearchOutputMode::List
    } else if raw.full {
        SearchOutputMode::Full
    } else {
        SearchOutputMode::Matches
    };
    let color_setting = raw.color.as_deref().unwrap_or("auto");
    // Python: `metadata_color = color != "never"` for a string choice, which is
    // resolved separately from `color` and does not follow it.
    let metadata_color = color_setting != "never";
    let mut color = match color_setting {
        "always" => true,
        "never" => false,
        _ => std::io::stdout().is_terminal(),
    };
    let mut paging = raw.paging.unwrap_or(color);
    if output_mode == SearchOutputMode::OnlyId || raw.raw {
        color = false;
        paging = false;
    }

    normalize_role_visibility(&mut raw, warnings);
    let selection = if raw.only_user && raw.only_assistant {
        MessageSelection::None
    } else if raw.only_user {
        MessageSelection::OnlyUser
    } else if raw.only_assistant {
        MessageSelection::OnlyAssistant
    } else {
        MessageSelection::All
    };
    let show_thinking = raw.all || raw.thinking_present;
    let shorten_thinking = !raw.all && raw.thinking.as_deref() == Some("short");
    if let Some(thinking) = raw.thinking.as_deref() {
        if !matches!(thinking, "full" | "short") {
            return SearchOutcome::Error(format!(
                "Invalid thinking mode: {}. Expected one of: full, short.",
                python_quoted(thinking)
            ));
        }
    }
    let short = match resolve_short_policy(&raw) {
        Ok(short) => short,
        Err(error) => return SearchOutcome::Error(error),
    };
    let tools = match build_tool_visibility(&raw.tool_values, raw.all) {
        Ok(tools) => tools,
        Err(error) => return SearchOutcome::Error(error),
    };
    let short_policy = short.unwrap_or_else(crate::shortening::default_short_policy);
    let flags = ConversationFlags {
        message_selection: selection,
        show_thinking,
        shorten_thinking,
        metadata_color,
        show_tools: tools,
        show_agents: raw.agents || raw.all,
        show_custom: raw.all,
        show_branches: raw.branches || raw.all,
        show_plans: raw.plans || raw.all,
        allow_empty_output: false,
        shorten: short.is_some(),
        shorten_max_chars: short_policy.max_chars,
        shorten_progressive: short_policy.progressive,
        color,
        paging,
    };
    SearchOutcome::Run(Box::new(SearchArguments {
        pattern,
        case_sensitive: raw.case_sensitive,
        output_mode,
        raw_output: raw.raw,
        emit_metadata: !(raw.no_metadata || raw.raw),
        flags,
        pool_filter: SearchPoolFilter {
            directory: raw.directory,
            modified_after: raw.modified_after,
            created_after: raw.created_after,
            provider: raw.provider,
        },
    }))
}

/// Port of `_normalize_role_visibility_args`: warns about overridden
/// visibility flags and resets them exactly like the Python original.
fn normalize_role_visibility(raw: &mut RawArguments, warnings: &mut Vec<String>) {
    fn disabled_flags(raw: &RawArguments) -> Vec<&'static str> {
        let mut disabled = Vec::new();
        if raw.all {
            disabled.push("`--all`");
        }
        if raw.thinking_present {
            disabled.push("`--thinking`");
        }
        if !raw.tool_values.is_empty() {
            disabled.push("`--tools`");
        }
        if raw.agents {
            disabled.push("`--agents`");
        }
        if raw.plans {
            disabled.push("`--plans`");
        }
        disabled
    }
    if raw.only_assistant {
        let disabled = disabled_flags(raw);
        if !disabled.is_empty() {
            warnings.push(format!(
                "Warning: `--only-assistant` overrides {}; disabling those options.",
                disabled.join(", ")
            ));
            reset_overridden_visibility(raw);
        }
    }
    if raw.only_user {
        let disabled = disabled_flags(raw);
        if !disabled.is_empty() {
            warnings.push(format!(
                "Warning: `--only-user` overrides {}; disabling those options.",
                disabled.join(", ")
            ));
            reset_overridden_visibility(raw);
        }
    }
    if raw.only_user && raw.only_assistant {
        warnings.push(
            "Warning: `--only-user` and `--only-assistant` are contradictory; \
             continuing with both filters active."
                .to_string(),
        );
    }
}

fn reset_overridden_visibility(raw: &mut RawArguments) {
    raw.all = false;
    raw.thinking_present = false;
    raw.thinking = None;
    raw.tool_values.clear();
    raw.agents = false;
    raw.plans = false;
}

fn resolve_short_policy(raw: &RawArguments) -> Result<Option<ShortPolicy>, String> {
    if !raw.short_present {
        return Ok(None);
    }
    crate::shortening::resolve_short_policy(
        raw.short_text.as_deref(),
        raw.short_text.is_none(),
    )
}

fn build_tool_visibility(
    values: &[Option<String>],
    show_all: bool,
) -> Result<ToolVisibility, String> {
    if show_all {
        return Ok(ToolVisibility::All(true));
    }
    if values.is_empty() {
        return Ok(ToolVisibility::All(false));
    }
    let specs = values
        .iter()
        .filter_map(Option::as_ref)
        .flat_map(|value| value.split_whitespace())
        .collect::<Vec<_>>();
    if specs.is_empty() {
        return Ok(ToolVisibility::All(true));
    }
    specs
        .into_iter()
        .map(|spec| crate::tool_filter::parse_tool_spec(spec))
        .collect::<Result<Vec<_>, _>>()
        .map(ToolVisibility::Filters)
}

fn repair_short_positional(raw: &mut RawArguments) {
    let candidate = match raw.short_text.clone() {
        Some(candidate) => candidate,
        None => return,
    };
    if raw.short_attached || crate::shortening::is_valid_short_max_chars_token(&candidate) || looks_like_short_spec(&candidate) {
        return;
    }
    if raw.pattern.is_none() {
        raw.pattern = Some(candidate);
        raw.short_text = None;
    }
}

fn normalize_option_tokens(tokens: Vec<String>) -> Result<Vec<String>, String> {
    let mut normalized = Vec::new();
    let mut options_enabled = true;
    for token in tokens {
        if options_enabled && token == "--" {
            options_enabled = false;
            normalized.push(token);
            continue;
        }
        if options_enabled && token.starts_with("--") {
            let (name, attached) = token
                .split_once('=')
                .map_or((token.as_str(), None), |(name, value)| (name, Some(value)));
            let mut matching = LONG_OPTIONS
                .iter()
                .filter(|option| option.name.starts_with(name))
                .collect::<Vec<_>>();
            if let Some(exact) = matching.iter().find(|option| option.name == name).copied() {
                matching = vec![exact];
            }
            if matching.len() > 1 {
                return Err(format!(
                    "ambiguous option: {name} could match {}",
                    matching
                        .iter()
                        .map(|option| option.name)
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            let Some(option) = matching.first() else {
                normalized.push(token);
                continue;
            };
            if option.arity == Arity::Flag {
                if let Some(value) = attached {
                    return Err(format!(
                        "argument {}: ignored explicit argument '{}'",
                        option.name,
                        value.replace('\'', "\\'")
                    ));
                }
            }
            normalized.push(match attached {
                Some(value) => format!("{}={value}", option.name),
                None => option.name.to_string(),
            });
            continue;
        }
        if options_enabled {
            if let Some(expanded) = expand_short_token(&token) {
                normalized.extend(expanded);
                continue;
            }
        }
        normalized.push(token);
    }
    Ok(normalized)
}

fn expand_short_token(token: &str) -> Option<Vec<String>> {
    if token == "-"
        || !token.starts_with('-')
        || token.starts_with("--")
        || is_argparse_negative_number(token)
    {
        return None;
    }
    if SHORT_OPTIONS.contains(&token) {
        return Some(vec![token.to_string()]);
    }
    let mut expanded = Vec::new();
    let mut cursor = 1;
    while cursor < token.len() {
        let remainder = &token[cursor..];
        let one_character_name = remainder
            .chars()
            .next()
            .map(|character| format!("-{character}"));
        let option = one_character_name
            .as_deref()
            .filter(|name| SHORT_OPTIONS.contains(name))
            .map(str::to_string)
            .or_else(|| {
                SHORT_OPTIONS
                    .iter()
                    .filter(|candidate| remainder.starts_with(&candidate[1..]))
                    .max_by_key(|candidate| candidate.len())
                    .map(|candidate| candidate.to_string())
            })?;
        cursor += option.len() - 1;
        match short_arity(&option).expect("table names always carry an arity") {
            Arity::Flag => expanded.push(option.clone()),
            Arity::Required => {
                if cursor == token.len() {
                    expanded.push(option.clone());
                } else {
                    let value = token[cursor..].strip_prefix('=').unwrap_or(&token[cursor..]);
                    expanded.push(format!("{option}={value}"));
                }
                return Some(expanded);
            }
            Arity::Optional => {
                expanded.push(format!("{option}{}", &token[cursor..]));
                return Some(expanded);
            }
        }
    }
    Some(expanded)
}

fn option_matches(token: &str, long: &str, shorts: &[&str]) -> bool {
    let name = token.split_once('=').map_or(token, |(name, _)| name);
    name == long || shorts.contains(&name)
}

fn optional_option_matches(token: &str, long: &str, short: &str) -> bool {
    let name = token.split_once('=').map_or(token, |(name, _)| name);
    token.starts_with(short) || name == long
}

fn long_optional_matches(token: &str, long: &str) -> bool {
    let name = token.split_once('=').map_or(token, |(name, _)| name);
    name == long
}

fn required_value(tokens: &[String], index: usize) -> Option<(String, usize)> {
    let token = &tokens[index];
    if let Some((_, value)) = token.split_once('=') {
        return Some((value.to_string(), 1));
    }
    let value = tokens.get(index + 1)?;
    if value.starts_with('-') && !is_argparse_negative_number(value) {
        return None;
    }
    Some((value.clone(), 2))
}

fn optional_value(tokens: &[String], index: usize, prefix: &str) -> (Option<String>, usize, bool) {
    let token = &tokens[index];
    if !prefix.starts_with("--") && token.starts_with(prefix) && token.len() > prefix.len() {
        return (Some(token[prefix.len()..].to_string()), 1, true);
    }
    if let Some((_, value)) = token.split_once('=') {
        return (Some(value.to_string()), 1, true);
    }
    let Some(next) = tokens.get(index + 1) else {
        return (None, 1, false);
    };
    if next.starts_with('-') && !is_argparse_negative_number(next) {
        return (None, 1, false);
    }
    (Some(next.clone()), 2, false)
}

fn is_argparse_negative_number(value: &str) -> bool {
    let Some(unsigned) = value.strip_prefix('-') else {
        return false;
    };
    if !unsigned.is_empty() && unsigned.chars().all(|character| character.is_ascii_digit()) {
        return true;
    }
    let Some((whole, fraction)) = unsigned.split_once('.') else {
        return false;
    };
    (whole.is_empty() || whole.chars().all(|character| character.is_ascii_digit()))
        && !fraction.is_empty()
        && fraction.chars().all(|character| character.is_ascii_digit())
}

fn python_quoted(value: &str) -> String {
    format!("'{}'", value.replace('\'', "\\'"))
}


#[cfg(test)]
mod argparse_parity {
    use super::*;
    use std::path::PathBuf;
    use std::process::Command;

    /// Shapes whose outcome the grammar alone decides: every error, plus help,
    /// plus the positionals argparse accepts. Cases that reach the pool need the
    /// engine and are not decidable here.
    const CASES: &[&[&str]] = &[
        &[],
        &["needle", "extra"],
        &["needle", "--bogus"],
        &["-s", "-i", "needle"],
        &["--color", "bogus", "needle"],
        &["-p", "bogus", "needle"],
        &["-T", "bogus", "needle"],
        &["--help"],
        &["-h"],
        &["-"],
        &["--", "needle"],
        &["needle"],
    ];

    fn argparse(tokens: &[&str]) -> (i32, String) {
        let oracle = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(".venv/bin/ch-legacy");
        assert!(oracle.exists(), "Expected the Python oracle at {oracle:?}.");
        let home = std::env::temp_dir().join("ch-grammar-parity-home");
        std::fs::create_dir_all(&home).expect("create isolated home");
        let output = Command::new(&oracle)
            .arg("search")
            .args(tokens)
            .env("HOME", &home)
            .env("COLUMNS", "96")
            .stdin(std::process::Stdio::null())
            .output()
            .expect("run the Python oracle");
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        // Precondition, not a comparison: the oracle imports `chats` from the live
        // `src/` tree that other sessions edit, so a mid-save crash yields a
        // traceback and an empty stdout. Without this the failure accuses the
        // parser instead of naming the crash.
        //
        // Deliberately not `status.success()`: argparse legitimately exits 2 on a
        // rejected argv, and that status is what the caller compares.
        assert!(
            !stderr.contains("Traceback (most recent call last):"),
            "The Python oracle crashed rather than disagreeing. stderr:\n{stderr}"
        );
        (output.status.code().unwrap_or(-1), stderr)
    }

    fn outcome(tokens: &[&str]) -> SearchOutcome {
        let argv: Vec<OsString> = tokens.iter().map(OsString::from).collect();
        parse_search_arguments(&argv).outcome
    }

    #[test]
    fn every_grammar_decidable_case_agrees_with_argparse() {
        for tokens in CASES {
            let (status, stderr) = argparse(tokens);
            match outcome(tokens) {
                SearchOutcome::Error(message) => {
                    assert_eq!(status, 2, "argparse accepted {tokens:?}; we rejected it.");
                    let expected = stderr
                        .split_once("ch search: error: ")
                        .expect("argparse error carries its marker")
                        .1
                        .trim_end_matches('\n');
                    assert_eq!(
                        message, expected,
                        "Error text diverged from argparse for {tokens:?}."
                    );
                }
                SearchOutcome::Help => assert_eq!(
                    status, 0,
                    "Treated {tokens:?} as help where argparse did not."
                ),
                SearchOutcome::Run(_) => assert_ne!(
                    status, 2,
                    "argparse rejected {tokens:?}; we accepted it."
                ),
            }
        }
    }

    // Found by the oracle, not by reading: argparse treats a lone `-` as a
    // positional by the stdin convention, so it becomes the pattern. The ported
    // parser rejected it as an unrecognized option.
    #[test]
    fn a_lone_dash_is_the_pattern_not_an_unknown_option() {
        assert!(
            matches!(outcome(&["-"]), SearchOutcome::Run(_)),
            "Expected a lone `-` to parse as the search pattern."
        );
    }
}

#[cfg(test)]
mod pool_filter_emptiness {
    use super::*;

    fn filter(directory: Option<&str>, mafter: Option<&str>) -> SearchPoolFilter {
        SearchPoolFilter {
            directory: directory.map(str::to_string),
            modified_after: mafter.map(str::to_string),
            created_after: None,
            provider: None,
        }
    }

    /// Measured against `ch-legacy`: `-d ""` gives the unfiltered wording,
    /// `-d /tmp/g` gives "with the current filters".
    #[test]
    fn an_empty_string_filter_counts_as_no_filter() {
        assert!(filter(None, None).is_empty(), "no filter at all is empty");
        assert!(
            filter(Some(""), None).is_empty(),
            "Python tests truthiness, so an empty `-d` is absent and takes the plain wording."
        );
        assert!(
            filter(Some(""), Some("")).is_empty(),
            "An empty `-ma` is absent for the wording, even though the date path still rejects it."
        );
        assert!(!filter(Some("/tmp/g"), None).is_empty(), "a real directory narrows the pool");
        assert!(!filter(None, Some("1d")).is_empty(), "a real date narrows the pool");
    }
}
